-- Table: public.article

DROP TABLE IF EXISTS public.article;

CREATE TABLE IF NOT EXISTS public.article
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    full_text text COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT article_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.article
    OWNER to postgres;

INSERT INTO public.article(title, full_text)
	VALUES ('At least 8 dead and many injured after crowd surge at Travis Scott''s Astroworld Festival in Houston', 'Houston (CNN)Members of a densely packed crowd surged toward a stage and were crushed against each other at a Houston music festival Friday night. At least eight people were killed and scores of others were injured in the chaos, witnesses and officials said.
The victims were 14, 16, two were 21, two were 23 and one was 27 years old, while one of the victim''s ages remains unknown, Houston Mayor Sylvester Turner announced in a news conference Saturday evening. There are no people reported missing, the mayor added.
At least 25 people were transported to the hospital and of those, 13 remained hospitalized Saturday afternoon, the mayor said. Five of them are under 18 years old, he added.
"There are a lot of unanswered questions," Turner said. "Over the next several days, several weeks, could be even longer, we''ll take an in-depth look at everything that took place, why it took place, what steps we can do moving forward to mitigate an incident of this kind from taking place."');

INSERT INTO public.article(title, full_text)
	VALUES ('Crisis worsens on Poland-Belarus border as migrants congregate and troops are mobilized', 'Tensions are escalating on the border between Poland and Belarus, after Polish officials again accused their neighbor of helping move migrants toward the frontier, and warned that thousands of additional military personnel have been mobilized to respond to confrontations.

In the latest in a weeks-long migration crisis at the border, the head of the Polish border guard said that groups of people were attempting to breach the border on Monday evening.
"The situation at the border is difficult. More numerous groups of migrants are led to the border. Attempts are being made to force the border through," Ewelina Szczepańska said, adding that she was confident that Polish forces could handle the situation.
Poland''s defense ministry said earlier on Monday on Twitter that "a group of migrants is currently located close to Kuznica." The post was accompanied by aerial footage showing large crowds congregating on the Belarusian side of the border. The ministry added later that: "Currently, migrants have set up a camp in the Kuznica region. They are constantly guarded by the Belarusian services."
The spokesman for the general headquarters of the Polish Border Guard, Michał Tokarczyk, told CNN: "Belarusian services are moving large groups of migrants towards the Polish border. We are waiting for their further move and we are prepared for any scenario."
In a follow-up statement, Tokarczyk specified that there are currently around 4,500 border guards and about 9,500 Polish Army soldiers stationed at the border as "a group of several thousand migrants is heading towards the Polish border."The Belarus State Border Committee, which is responsible for the country''s external borders, said the migrants near the border want to enter Poland as refugees and do not pose a security threat.
A growing number of people have been illegally crossing Poland''s border from Belarus in recent weeks. According to Tokarczyk, since August more than 30,000 migrants have attempted to enter the country.
Belarusian leader Alexander Lukashenko has previously been accused of manufacturing a migrant crisis on the border by the Prime Ministers of neighbors Poland, Latvia and Lithuania, leading Poland to adopt a bill in October for the construction of a wall along its border with Belarus.
European officials have also accused Belarus of encouraging people to cross illegally into Poland, and its other European Union neighbors, as part of efforts to put pressure on the bloc over sweeping sanctions it imposed on Minsk in June. The sanctions by the EU, the US and Britain were a coordinated response to the Lukashenko government''s forced landing of a Ryanair flight and arrest of an opposition journalist on board, as well as "continuing repression" in the former Soviet state.');